name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Validate HTML
      run: |
        # Install HTML validator
        npm install -g html-validate
        
        # Validate the HTML file
        html-validate index.html
    
    - name: Security headers check
      run: |
        # Check for potential security issues in HTML
        if grep -i "javascript:" index.html; then
          echo "Warning: Found javascript: protocol usage"
          exit 1
        fi
        
        if grep -i "eval(" index.html; then
          echo "Warning: Found eval() usage"
          exit 1
        fi
        
        if grep -i "innerHTML.*\+" index.html; then
          echo "Warning: Found potential XSS vulnerability with innerHTML concatenation"
          exit 1
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4