name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to gh-pages branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Validate HTML
      run: |
        # Install HTML validator
        npm install -g html-validate
        
        # Validate the HTML file
        html-validate index.html
    
    - name: Security headers check
      run: |
        # Check for potential security issues in HTML
        if grep -i "javascript:" index.html; then
          echo "Warning: Found javascript: protocol usage"
          exit 1
        fi
        
        if grep -i "eval(" index.html; then
          echo "Warning: Found eval() usage"
          exit 1
        fi
        
        if grep -i "innerHTML.*+.*[\"']" index.html; then
          echo "Warning: Found potential XSS vulnerability with innerHTML concatenation"
          exit 1
        fi
    
    - name: Prepare deployment directory
      run: |
        mkdir -p dist
        cp index.html dist/
        cp LICENSE dist/ 2>/dev/null || true
        cp README.md dist/ 2>/dev/null || true
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        force_orphan: true