name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to gh-pages branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Validate HTML
      run: |
        # Install HTML validator
        npm install -g html-validate

        # Validate the HTML file
        html-validate web/index.html

    - name: Security headers check
      run: |
        # Check for potential security issues in HTML
        if grep -i "javascript:" web/index.html; then
          echo "Warning: Found javascript: protocol usage"
          exit 1
        fi

        if grep -i "eval(" web/index.html; then
          echo "Warning: Found eval() usage"
          exit 1
        fi

        if grep -i "innerHTML.*+.*[\"']" web/index.html; then
          echo "Warning: Found potential XSS vulnerability with innerHTML concatenation"
          exit 1
        fi

    - name: Prepare deployment directory
      run: |
        mkdir -p dist
        cp web/index.html dist/
        cp LICENSE dist/ 2>/dev/null || true
        cp README.md dist/ 2>/dev/null || true

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
        force_orphan: true
